import smtplib
from email import encoders
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# define the SMTP server:
port = 2525
smtp_server = "smtp.mailtrap.io"
login = "59115f80138569" # login generated by Mailtrap
password = "2cc4299cf77e32" # password generated by Mailtrap

# sender’s and receiver’s email addresses
sender_email = "Private Person <from@smtp.mailtrap.io>"
receiver_email = "A Test User <to@smtp.mailtrap.io>"

message = MIMEMultipart()
message["Subject"] = "An example of boarding pass"
message["From"] = sender_email
message["To"] = receiver_email

# Add body to email
body = "This is an example of how you can send a boarding pass in attachment with Python"
message.attach(MIMEText(body, "plain"))

filename = "strange_weather_science_gallery.pdf"
# Open PDF file in binary mode
# We assume that the file is in the directory where you run your Python script from
with open(filename, "rb") as attachment:
    # The content type "application/octet-stream" means that a MIME attachment is a binary file
    part = MIMEBase("application", "octet-stream")
    part.set_payload(attachment.read())

# Encode to base64
encoders.encode_base64(part)

# Add header
part.add_header(
    "Content-Disposition",
    f"attachment; filename= {filename}",
)

# Add attachment to your message and convert it to string
message.attach(part)  # To attach several files, you can call the message.attach() method several times.
text = message.as_string()

# send your email
with smtplib.SMTP(smtp_server, port) as server:
    server.login(login, password)
    server.sendmail(sender_email, receiver_email, text)
print('Sent')