import smtplib
from email.mime.text import MIMEText  # better to write a text version and an HTML version separately, and then merge them with the MIMEMultipart(“alternative”) instance
from email.mime.multipart import MIMEMultipart

# define the SMTP server:
port = 2525
smtp_server = "smtp.mailtrap.io"
login = "59115f80138569" # login generated by Mailtrap
password = "2cc4299cf77e32" # password generated by Mailtrap

# sender’s and receiver’s email addresses
sender_email = "Private Person <from@smtp.mailtrap.io>"
receiver_email = "A Test User <to@smtp.mailtrap.io>"

message = MIMEMultipart("alternative")
message["Subject"] = "multipart test"
message["From"] = sender_email
message["To"] = receiver_email

text = """\
Hi,
Check out the new post on the Mailtrap blog:
SMTP Server for Testing: Cloud-based or Local?
https://blog.mailtrap.io/2018/09/27/cloud-or-local-smtp-server/
Feel free to let us know what content would be useful for you!"""

# write the HTML part
html = """\
<html>
  <body>
    <p>Hi,<br>
       Check out the new post on the Mailtrap blog:</p>
    <p><a href="https://blog.mailtrap.io/2018/09/27/cloud-or-local-smtp-server">SMTP Server for Testing: Cloud-based or Local?</a></p>
    <p> Feel free to <strong>let us</strong> know what content would be useful for you!</p>
  </body>
</html>
"""

# convert both parts to MIMEText objects and add them to the MIMEMultipart message
part1 = MIMEText(text, "plain")
part2 = MIMEText(html, "html")
message.attach(part1)
message.attach(part2)

# send your email
with smtplib.SMTP(smtp_server, port) as server:
    server.login(login, password)
    server.sendmail(
        sender_email, receiver_email, message.as_string()
    )
print('Sent')