import smtplib  # built-in module for sending emails
from socket import gaierror  # add some error handling

help(smtplib)  # make sure that the module has been imported properly and get the full description of its classes and arguments

# define the SMTP server:
port = 2525
smtp_server = "smtp.mailtrap.io"
login = "59115f80138569" # login generated by Mailtrap
password = "2cc4299cf77e32" # password generated by Mailtrap

# sender’s and receiver’s email addresses
sender_email = "Private Person <from@smtp.mailtrap.io>"
receiver_email = "A Test User <to@smtp.mailtrap.io>"

# type your message: use two newlines (\n) to separate the subject from the message body
message = f"""\
Subject: Hi Mailtrap
To: {receiver_email}
From: {sender_email}

Send another love mail from PyCharm."""

try:
    # send your message with credentials specified above
    with smtplib.SMTP(smtp_server, port) as server:
        server.login(login, password)
        server.sendmail(sender_email, receiver_email, message)

    # tell the script to report if your message was sent or which errors need to be fixed
    print('Sent')
except (gaierror, ConnectionRefusedError):
    print('Failed to connect to the server. Bad connection settings?')
except smtplib.SMTPServerDisconnected:
    print('Failed to connect to the server. Wrong user/password?')
except smtplib.SMTPException as e:
    print('SMTP error occurred: ' + str(e))
